"""Reusable vocabulary."""

from collections.abc import Sequence

from curies import vocabulary as _v

from ..identifier_utils import Reference

__all__ = [
    "CHARLIE",
    "equivalent_class",
    "has_contributor",
    "mapping_has_confidence",
    "mapping_has_justification",
]

RO_PREFIX = "RO"
BFO_PREFIX = "BFO"


broad_match = Reference.from_reference(_v.broad_match)
close_match = Reference.from_reference(_v.close_match)
exact_match = Reference.from_reference(_v.exact_match)
narrow_match = Reference.from_reference(_v.narrow_match)
related_match = Reference.from_reference(_v.related_match)

has_related_synonym = Reference.from_reference(_v.has_related_synonym)
has_exact_synonym = Reference.from_reference(_v.has_exact_synonym)
has_narrow_synonym = Reference.from_reference(_v.has_narrow_synonym)
has_broad_synonym = Reference.from_reference(_v.has_broad_synonym)

mapping_has_justification = Reference(
    prefix="sssom", identifier="mapping_justification", name="mapping justification"
)
mapping_has_confidence = Reference(prefix="sssom", identifier="confidence", name="has confidence")
has_contributor = Reference.from_reference(_v.has_contributor)
has_creator = Reference(prefix="dcterms", identifier="creator", name="creator")
has_source = Reference.from_reference(_v.has_source)
has_date = Reference.from_reference(_v.has_date)
has_dbxref = Reference.from_reference(_v.has_dbxref)

in_subset = Reference.from_reference(_v.obo_in_subset)
has_obo_namespace = Reference.from_reference(_v.obo_has_namespace)
obo_is_metadata_tag = Reference(
    prefix="oboinowl", identifier="is_metadata_tag", name="is metadata tag"
)
obo_has_id = Reference(prefix="oboinowl", identifier="id", name="has ID")
obo_has_format_version = Reference(
    prefix="oboinowl", identifier="hasOBOFormatVersion", name="has OBO format version"
)
obo_autogenerated_by = Reference.from_reference(_v.obo_autogenerated_by)
obo_creation_date = Reference.from_reference(_v.obo_creation_date)
obo_consider = Reference(prefix="oboinowl", identifier="consider", name="consider")

equivalent_class = Reference.from_reference(_v.equivalent_property)
equivalent_property = Reference.from_reference(_v.equivalent_class)
owl_same_as = Reference.from_reference(_v.same_as)
version_info = Reference.from_reference(_v.owl_version_info)
term_replaced_by = Reference.from_reference(_v.term_replaced_by)
alternative_term = Reference.from_reference(_v.alternative_term)
has_ontology_root_term = Reference.from_reference(_v.has_ontology_root_term)
has_ontology_hierarchy_predicate = Reference.from_reference(_v.has_ontology_hierarchical_property)
has_term_editor = Reference.from_reference(_v.has_term_editor)
term_tracker_item = Reference.from_reference(_v.term_tracker_item)

see_also = Reference.from_reference(_v.see_also)
comment = Reference.from_reference(_v.has_comment)
label = Reference.from_reference(_v.has_label)

from_species = Reference(prefix=RO_PREFIX, identifier="0002162", name="in taxon")
species_specific = Reference(prefix="debio", identifier="0000007", name="species specific")
has_left_to_right_reaction = Reference(
    prefix="debio", identifier="0000007", name="has left-to-right reaction"
)
has_right_to_left_reaction = Reference(
    prefix="debio", identifier="0000008", name="has right-to-left reaction"
)
debio_has_inchi = Reference(prefix="debio", identifier="0000020", name="has InChI")
has_inchi = Reference(prefix="chemrof", identifier="inchi_string")

debio_has_smiles = Reference(prefix="debio", identifier="0000022", name="has SMILES")
has_smiles = Reference(prefix="chemrof", identifier="smiles_string")
has_canonical_smiles = Reference(prefix="chemrof", identifier="canonical_smiles_string")
has_isomeric_smiles = Reference(prefix="chemrof", identifier="isomeric_smiles_string")

document = Reference.from_curie("IAO:0000310", name="document")
is_mentioned_by = Reference(prefix="mito", identifier="isMentionedBy", name="is mentioned by")
mentions = Reference(prefix="mito", identifier="mentions", name="mentions")

has_description = Reference.from_reference(_v.has_description)
has_license = Reference.from_reference(_v.has_license)
has_license = Reference.from_reference(_v.has_license)
has_title = Reference.from_reference(_v.has_title)

has_homepage = Reference(prefix="foaf", identifier="homepage", name="has homepage")
has_logo = Reference(prefix="foaf", identifier="logo", name="has logo")
has_mailbox = Reference(prefix="foaf", identifier="mbox", name="has mailbox")
has_depiction = Reference(prefix="foaf", identifier="depicted_by", name="depicted by")
has_repository = Reference(prefix="doap", identifier="repository", name="has repository")
has_mailing_list = Reference(prefix="doap", identifier="mailing-list", name="has mailing list")
has_maintainer = Reference(prefix="doap", identifier="maintainer", name="has maintainer")

has_suborganization = Reference.from_reference(_v.has_suborganization)
is_suborganization_of = Reference.from_reference(_v.is_suborganization_of)

has_part = Reference(prefix=BFO_PREFIX, identifier="0000051", name="has part")
part_of = Reference(prefix=BFO_PREFIX, identifier="0000050", name="part of")
orthologous = Reference(
    prefix=RO_PREFIX, identifier="HOM0000017", name="in orthology relationship with"
)
is_a = Reference.from_reference(_v.is_a)
subproperty_of = Reference.from_reference(_v.subproperty_of)
rdf_type = Reference.from_reference(_v.rdf_type)

xsd_string = Reference.from_reference(_v.xsd_string)
xsd_float = Reference.from_reference(_v.xsd_float)
xsd_decimal = Reference.from_reference(_v.xsd_decimal)
xsd_integer = Reference.from_reference(_v.xsd_integer)
xsd_boolean = Reference.from_reference(_v.xsd_boolean)
xsd_year = Reference.from_reference(_v.xsd_year)
xsd_uri = Reference.from_reference(_v.xsd_uri)

CHARLIE = Reference.from_reference(_v.charlie)
HUMAN = Reference.from_reference(_v.human)

#: See https://mapping-commons.github.io/sssom/spec-model/
match_typedefs: Sequence[Reference] = (
    broad_match,
    close_match,
    exact_match,
    narrow_match,
    related_match,
    owl_same_as,  # for instances
    equivalent_class,  # for classes
    equivalent_property,  # for properties
    has_dbxref,
    see_also,
)

# Extension past the SSSOM spec
extended_match_typedefs: Sequence[Reference] = (
    *match_typedefs,
    alternative_term,
    term_replaced_by,
)

#: These are predicates that have their own dedicated fields
#: in OBO and FunOWL output
SKIP_PROPERTY_PREDICATES_OBJECTS = [
    term_replaced_by,  # maps to "replaced_by:" line
    alternative_term,  # maps to "alt_id:" line
    obo_consider,  # maps to ``consider`` tag
]

SKIP_PROPERTY_PREDICATES_LITERAL = [
    comment,  # maps to "comment:" line with strings
    obo_creation_date,
]

mouse = Reference(prefix="NCBITaxon", identifier="10090", name="Mus musculus")
rat = Reference(prefix="NCBITaxon", identifier="10116", name="Rattus norvegicus")
gene = Reference(prefix="SO", identifier="0000704", name="gene")
GENE_GROUP = Reference(prefix="SO", identifier="0005855", name="gene group")
protein = Reference(prefix="PR", identifier="000000001", name="protein")
molecular_function = Reference(prefix="GO", identifier="0003674", name="molecular function")
rna = Reference(prefix="uniprot.core", identifier="RNA", name="RNA")
chromosomal_region = Reference(prefix="GO", identifier="0098687", name="chromosomal region")
chemical = Reference(prefix="chebi", identifier="24431", name="chemical entity")
