sudo: true
cache: pip
dist: xenial
language: python
python:
  - '3.6'
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=pyroma
    - env: TOXENV=mypy
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs
    # test stage
    - stage: test
      env: TOXENV=py
  allow_failures:
    - env: TOXENV=mypy
    - env: TOXENV=py

install:
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov; else pip install tox; fi'

script:
  - tox

after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'
