"""Test cases."""

import tempfile
import unittest
from abc import ABC, abstractmethod
from collections.abc import Iterable
from pathlib import Path
from textwrap import dedent
from typing import Literal

import robot_obo_tool

from pyobo.struct.struct import Obo, Term, TypeDef

__all__ = [
    "TermMixin",
    "TestMixin",
]


class TestMixin(unittest.TestCase):
    """Test ontologies."""

    def assert_lines(self, text: str, lines: Iterable[str]) -> None:
        """Assert the lines are equal."""
        self.assertEqual(dedent(text).strip(), "\n".join(lines).strip())

    def assert_obo_lines(self, text: str, ontology: Obo) -> None:
        """Assert OBO header has the right lines."""
        self.assert_lines(text, ontology.iterate_obo_lines())

    def assert_obo_equal(self, expected: Obo, ontology: Obo) -> None:
        """Assert two OBO documents are equivalent by exporting them."""
        self.assertEqual(
            "\n".join(expected.iterate_obo_lines()),
            "\n".join(ontology.iterate_obo_lines()),
        )

    def assert_ofn_lines(self, text: str, ontology: Obo, *, oracle: bool = False) -> None:
        """Assert OFN header has the right lines."""
        with tempfile.TemporaryDirectory() as directory:
            in_path = Path(directory).joinpath("tmp.ofn")
            if oracle:
                tmp_path = Path(directory).joinpath("tmp.obo")
                ontology.write_obo(tmp_path)
                robot_obo_tool.convert(tmp_path, in_path, check=True, debug=True)
            else:
                ontology.write_ofn(in_path)
            self.assert_lines(text, in_path.read_text().splitlines())

    def assert_owl_lines(
        self, text: str, ontology: Obo, *, method: Literal["ofn", "obo"] = "ofn"
    ) -> None:
        """Assert OWL header has the right lines."""
        with tempfile.TemporaryDirectory() as directory:
            if method == "ofn":
                in_path = Path(directory).joinpath("tmp.ofn")
                ontology.write_ofn(in_path)
            elif method == "obo":
                in_path = Path(directory).joinpath("tmp.obo")
                ontology.write_obo(in_path)
            else:
                raise ValueError(f"invalid method: {method}")
            out_path = Path(directory).joinpath("tmp.owl")
            robot_obo_tool.convert(in_path, out_path, check=True, debug=True)
            lines = out_path.read_text().splitlines()
            lines = [
                "" if not line.strip() else line.rstrip()
                for line in lines
                if line.strip() and not line.strip().startswith("<!-- Generated by the OWL API")
            ]
            self.assert_lines(text, lines)

    def get_only_term(self, ontology: Obo) -> Term:
        """Assert there is only a single term in the ontology and return it."""
        terms = list(ontology.iter_terms())
        self.assertEqual(1, len(terms))
        term = terms[0]
        return term

    def get_only_typedef(self, ontology: Obo) -> TypeDef:
        """Assert there is only a single typedef in the ontology and return it."""
        if ontology.typedefs is None:
            raise self.fail()
        self.assertEqual(1, len(ontology.typedefs))
        return ontology.typedefs[0]


class TermMixin(unittest.TestCase, ABC):
    """A mixin for testing all components of a term."""

    @abstractmethod
    def test_1_id(self) -> None:
        """Test the ``id`` tag."""

    @abstractmethod
    def test_2_is_anonymous(self) -> None:
        """Test the ``is-anonymous`` tag."""

    @abstractmethod
    def test_3_name(self) -> None:
        """Test the ``name`` tag."""

    @abstractmethod
    def test_4_namespace(self) -> None:
        """Test the ``namespace`` tag."""

    @abstractmethod
    def test_5_alt_id(self) -> None:
        """Test the ``alt_id`` tag."""

    @abstractmethod
    def test_6_definition(self) -> None:
        """Test the ``definition`` tag."""

    @abstractmethod
    def test_7_comment(self) -> None:
        """Test the ``comment`` tag."""

    @abstractmethod
    def test_8_subset(self) -> None:
        """Test the ``subset`` tag."""

    @abstractmethod
    def test_9_synonym(self) -> None:
        """Test the ``synonym`` tag."""

    @abstractmethod
    def test_10_xrefs(self) -> None:
        """Test the ``xref`` tag."""

    @abstractmethod
    def test_11_builtin(self) -> None:
        """Test the ``builtin`` tag."""

    @abstractmethod
    def test_12_property(self) -> None:
        """Test the ``property`` tag."""

    @abstractmethod
    def test_13_parent(self) -> None:
        """Test the ``parent`` tag."""

    @abstractmethod
    def test_14_intersection_of(self) -> None:
        """Test the ``intersection_of`` tag."""

    @abstractmethod
    def test_15_union_of(self) -> None:
        """Test the ``union_of`` tag."""

    @abstractmethod
    def test_16_equivalent_to(self) -> None:
        """Test the ``equivalent_to`` tag."""

    @abstractmethod
    def test_17_disjoint_from(self) -> None:
        """Test the ``disjoint_from`` tag."""

    @abstractmethod
    def test_18_relationship(self) -> None:
        """Test the ``relationship`` tag."""

    # TODO test_19_created_by

    @abstractmethod
    def test_20_creation_date(self) -> None:
        """Test the ``creation_date`` tag."""

    @abstractmethod
    def test_21_is_obsolete(self) -> None:
        """Test the ``is_obsolete`` tag."""

    @abstractmethod
    def test_22_replaced_by(self) -> None:
        """Test the ``replaced-by`` tag."""

    @abstractmethod
    def test_23_consider(self) -> None:
        """Test the ``consider`` tag."""
