name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.12" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          pip install tox
      - name: Check manifest
        run: tox -e manifest
      - name: Check code quality with flake8
        run: tox -e flake8
      - name: Check package metadata with Pyroma
        run: tox -e pyroma
      - name: Check static typing with MyPy
        run: tox -e mypy
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          pip install tox tox-uv
      - name: Check RST conformity with doc8
        run: tox -e doc8
      - name: Check README.rst
        run: tox -e doc8
      - name: Check documentation build with Sphinx
        run: tox -e docs-test
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9", "3.12" ]
        exclude:
          - os: windows-latest
            python-version: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          pip install tox tox-uv
      - name: Test with pytest
        run:
          tox -e py
